apiVersion: v1
kind: Service
metadata:
  name: wenk-test-1
  namespace: namespace-workflow-1734448954021
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: wenk-test-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80